### ISSUE TITLE
node-gyp errors on npm install

### ISSUE THREAD

**Issue by beardyman** [bhelx/mitie#3]
Hi, 

I'm getting node-gyp when I try to npm install this package and I'm not really sure how to move forward.  The error is as follows: 

```
> node-gyp rebuild

  CXX(target) Release/obj.target/mitie/src/mitie.o
In file included from ../src/mitie.cc:2:
../src/entity_extractor.h:5:10: fatal error: 'mitie/named_entity_extractor.h' file not found
#include <mitie/named_entity_extractor.h>
         ^
1 error generated.
```

I have installed mitie via homebrew and am using OS X El Capitan.  I'm using node 4.4.1 and npm 2.15.2.  Any help would be appreciated.

**Comment by bhelx** [comment]
Have you installed the mitie package on your system? You can use homebrew to do so:

```
brew install mitie
```

See the Installing section: https://github.com/bhelx/mitie#installing

**Comment by beardyman** [comment]
I have, although I just realized that I have homebrew installed through boxen so it is installed in a different place than it would normally be.  Could that be causing the issue?  Its currently installed at `/opt/boxen/homebrew/Cellar/mitie`.  I noticed in your `binding.gyp` you have `"/usr/local/include/mitie/",` which doesn't exist for me.  However I do have a `/opt/boxen/homebrew/include/mitie/`.

**Comment by bhelx** [comment]
Yes, I have it hard coded. You could either send a PR to fix it (possibly make it configurable or find some way to remove it) or a quick fix may be to just symlink the directory to your location owned by boxen.

**Comment by beardyman** [comment]
Worked like a charm.  Thanks!!!

**Comment by bhelx** [comment]
Cool! Glad it worked :)

**Comment by maxmert** [comment]
@bhelx @beardyman Hey guys, sorry for disturbing you.
Have the same problem, but symlink doesn't fix it.
(Linux 3.16.0-4-amd64 Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux)

``` bash
> mitie@1.0.0 install /var/www/dh-nlp/node_modules/mitie
> node-gyp rebuild

make: Entering directory '/var/www/dh-nlp/node_modules/mitie/build'
  CXX(target) Release/obj.target/mitie/src/mitie.o
In file included from ../mitie/dlib/dlib/serialize.h:157:0,
                 from /usr/local/include/mitie/approximate_substring_set.h:9,
                 from /usr/local/include/mitie/word_morphology_feature_extractor.h:7,
                 from /usr/local/include/mitie/total_word_feature_extractor.h:8,
                 from /usr/local/include/mitie/named_entity_extractor.h:7,
                 from ../src/entity_extractor.h:5,
                 from ../src/mitie.cc:2:
../mitie/dlib/dlib/smart_pointers/shared_ptr.h: In member function 'void* dlib::shared_ptr<T>::deleter_template<D>::get_deleter_void(const std::type_info&) const':
../mitie/dlib/dlib/smart_pointers/shared_ptr.h:112:29: error: cannot use typeid with -fno-rtti
                 if (typeid(D) == t)
                             ^
../mitie/dlib/dlib/smart_pointers/shared_ptr.h: In member function 'D* dlib::shared_ptr<T>::_get_deleter() const':
../mitie/dlib/dlib/smart_pointers/shared_ptr.h:432:83: error: cannot use typeid with -fno-rtti
                 return static_cast<D*>(shared_node->del->get_deleter_void(typeid(D)));
                                                                                   ^
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
mitie.target.mk:94: recipe for target 'Release/obj.target/mitie/src/mitie.o' failed
make: *** [Release/obj.target/mitie/src/mitie.o] Error 4
make: Leaving directory '/var/www/dh-nlp/node_modules/mitie/build'
```

**Comment by bhelx** [comment]
@maxmert I've never attempted a linux install. The process will likely be different.

**Comment by DenisDantsev** [comment]
@bhelx Could you please update repository with working version.
**1st** I had an issue with 'mitie/named_entity_extractor.h' file path - fixed by specific file path to /usr/local/Cellar/mitie/0.4/ etc. 
**2nd** - similar issue with dlib - fix by specific file path to source repo.

then I get warning and error here
../src/entity_extractor.cc:56:37: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                    ^
/Users/.../.node-gyp/6.6.0/include/node/v8.h:3270:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/entity_extractor.cc:77:13: error: no member named 'predict' in 'mitie::named_entity_extractor'
  obj->ner_.**predict**(tokens, chunks, chunk_tags, chunk_scores);

I am using Mac OS 10.12, node v6.6.0

**Comment by bhelx** [comment]
@DenisDantsev 

Are you installing from the npm repository? or have you cloned the project locally?

**Comment by DenisDantsev** [comment]
@bhelx First I tried installing with npm and after failures I cloned repository and tried to build it.

**Comment by bhelx** [comment]
I wasn't able to reproduce but I'm building on node5 right now. I'll try 6. For now please try something for me. From the cloned repository, run:

```
git submodule init
git submodule update ./mitie/
npm install
```

See if that build works.

**Comment by bhelx** [comment]
Also, are those warnings breaking the build? Or just warnings?

**Comment by DenisDantsev** [comment]
@bhelx I tried and got same results. Please try latest node version.

**Comment by bhelx** [comment]
@DenisDantsev I'm still seeing a successful build on node 6.6.0 (your version).

It appears that the gyp having trouble building my c extension portion. Maybe try looking at https://github.com/bhelx/mitie/blob/master/binding.gyp

You may want to check that "/usr/local/include/mitie/" points to where you think it should point (your homebrew installation). Mine looks like this:

```
~ ls /usr/local/include/mitie                                           
approximate_substring_set.h         named_entity_extractor.h
binary_relation_detector.h          ner_feature_extraction.h
binary_relation_detector_trainer.h  ner_trainer.h
conll_parser.h                      stemmer.h
conll_tokenizer.h                   total_word_feature_extractor.h
count_min_sketch.h                  unigram_tokenizer.h
gigaword_reader.h                   word_morphology_feature_extractor.h
group_tokenizer.h
```

```
~ ls -la /usr/local/include/ | grep mitie                                                  11:12:59
lrwxr-xr-x    1 ben   admin     33 Jul  8 10:57 mitie -> ../Cellar/mitie/0.4/include/mitie
lrwxr-xr-x    1 ben   admin     35 Jul  8 10:57 mitie.h -> ../Cellar/mitie/0.4/include/mitie.h
```

You may also consider trying editing some of these options.

**Comment by andrewnaeve** [comment]
would just like to add that I have the same problem, but I'm not clear on how to fix it.  OS Sierra 10.12.3, Node 6.9.4.

/usr/local/include/mitie  & /usr/local/include/ | grep mitie    look identical to yours. I installed on a work computer with no problem, but my machine just isn't having it.
